apiVersion: v2
name: octo-x
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
- name: guestbook
  version: "0.2.0"
  repository: "https://apphub.aliyuncs.com"
  condition: guestbook.enabled

- name: httpbingo
  version: "0.1.0"
  repository: "https://estahn.github.io/charts"
  condition: httpbingo.enabled

